### ISSUE TITLE
Error loading DICOM

### ISSUE THREAD

**Issue by mariabizev** [jpambrun/dcmj2k-streaming-viewer#2]
Hi there,

I believe I installed your library and all the dependencies correctly. However, when I view the index.html, the DICOM does not load and is instead empty. I've attached an image. 

Any help would be greatly appreciated!
![dicom viewer issue](https://cloud.githubusercontent.com/assets/16541998/14475688/3cd4aff8-00d1-11e6-8348-bd7390b19efb.png)

**Comment by jpambrun** [comment]
It is more of a tech demo. The dicom file URLs are hard coded, but not
include in the repo.

You will need to adapt the code for your needs.

You can see an somewhat earlier version in action here:

jpx.jfpb.net

**Comment by jpambrun** [comment]
You could change index.html:L221 [1]
from ../data to http://jpambrun.github.io/data/ and it should work with the
images hosted there.

In the end, you will need to modify a J2K encoder to produce truncable
streams embedded in DICOM files with the required DICOM tags.

[1]
https://github.com/jpambrun/dcmj2k-streaming-viewer/blob/master/src/index.html#L221

**Comment by jpambrun** [comment]
github.io does not allow CORS for byte range request.
It is now configured to stream files from my VPS.

**Comment by mariabizev** [comment]
Hi,

I apologize for my lack of understanding, but I am new to DICOM and  
J2K encoding. What I have is a multi-frame DICOM image (one file) and  
I also have the same set of images available in a .tif file. Can you  
give me steps regarding what to do with these files to format them  
correctly to be used with the DICOM-J2K viewer? Any resources or  
services you could send me would be incredibly helpful.

Thanks very much!

Quoting Jean Francois Pambrun notifications@github.com:

> You could change index.html:L221 [1]
> from ../data to http://jpambrun.github.io/data/ and it should work with the
> images hosted there.
> 
> In the end, you will need to modify a J2K encoder to produce truncable
> streams embedded in DICOM files with the required DICOM tags.
> 
> [1]
> https://github.com/jpambrun/dcmj2k-streaming-viewer/blob/master/src/index.html#L221
>

**Comment by jpambrun** [comment]
The viewing component leverage the cornerstone framework [1].
I have added support for JPEG 2000 in the upstream project.
If you just want to build a viewer with JPEG~2000 support, you should use
that.

This project was built to test new streaming techniques where the image is
progressively downloaded in order to improve performance and reduce
bandwidth usage.
However, in order to enable this, the JPEG2000 stream needs to be
reorganized and special markers must be added as private DICOM tags.
Unfortunately, the compression tools I have used are part of a ongoing
research project and I can't publish them at this time.

[1] https://github.com/chafey/cornerstone
